//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApi.Models
{
    using System;
    
    public partial class GetCity_Result2
    {
        public int CID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
